version: "3"
services:
  planetarium:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/planetarium
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - LANG=en_US.utf8
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5433:5432"
    env_file:
      - .env
